### ISSUE TITLE
Informação Estranha - Aplicações

### ISSUE THREAD

**Issue by tspadua** [joaoserralha/Sistema-de-Judocas#2]
Seção 4.4 da especificação de requisitos parece destacar quais aplicações abrangem o processo, fato desnecessário já que é um sistema de aplicação única. Da mesma forma, a seção 4.5.1 poderia ser apresentada apenas como 4.5.

Com essa alteração, a tabela 4.4 deixa de ser necessária pois os casos de uso são listados em seguida.

**Comment by joaoserralha** [comment]
Feito.
